version: 3.7build{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
cache:
  - externals -> PCbuild\*
before_build:
  - cmd: git diff --name-only
  # Can we exit early at all?
  - cmd: appveyor exit
build_script:
  - cmd: PCbuild\build.bat -e
  - cmd: PCbuild\win32\python.exe -m test.pythoninfo
test_script:
  - cmd: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest --timeout=1200 --fail-env-changed -j0
environment:
  HOST_PYTHON: C:\Python36\python.exe
image:
- Visual Studio 2017
