version: 3.7build{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
cache:
  - externals -> PCbuild\*
before_build:
  # Do we have grep?
  - cmd: where grep
  # Can we exit early at all?
  - cmd: set EXIT_EARLY=1
build_script:
  - cmd: if "%EXIT_EARLY%" EQU "1" echo hit
  - cmd: PCbuild\build.bat -e
  - cmd: PCbuild\win32\python.exe -m test.pythoninfo
test_script:
  - cmd: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest --timeout=1200 --fail-env-changed -j0
environment:
  HOST_PYTHON: C:\Python36\python.exe
image:
- Visual Studio 2017
